apiVersion: v1
data:
  cloud.conf: |
    [Global]
    use-clouds = true
    clouds-file = /etc/kubernetes/secret/clouds.yaml
    cloud = openstack
kind: ConfigMap
metadata:
  name: openstack-cinder-config
  namespace: openshift-cluster-csi-drivers
